query getActivitiesByUser($userId: Int!, $take: Int!, $activityType: String) {
  activities(userId: $userId, take: $take, activityType: $activityType) {
    id
    createdAt
    review {
      content
      rating
      user {
        id
        username
        firstName
        lastName
        avatarUrl
      }
      book {
        id
        slug
        coverUrl
        title
        authors {
          id
          firstName
          lastName
        }
      }
      socialMeta {
        id
        likes {
          id
        }
        comments {
          id
        }
      }
      createdAt
    }

    quote {
      content
      user {
        id
        username
        firstName
        lastName
        avatarUrl
      }
      book {
        id
        slug
        coverUrl
        title
        authors {
          id
          firstName
          lastName
        }
      }
      socialMeta {
        id
        likes {
          id
        }
        comments {
          id
        }
      }
      createdAt
    }

    bookList {
      name
      user {
        id
        username
        firstName
        lastName
        avatarUrl
      }
      books {
        id
        title
        coverUrl
      }
      socialMeta {
        id
        likes {
          id
        }
        comments {
          id
        }
      }
      createdAt
    }
  }
}
